#!/bin/bash

# Set the path to the Android NDK and SDK
ANDROID_SDK=~/Android/Sdk
ANDROID_HOME=$ANDROID_SDK
ANDROID_NDK_HOME=$ANDROID_SDK/ndk/android-ndk-r26d
ANDROID_OPENCL_SDK=~/OpenCV-4.11.0-src/ANDROID_OPENCL_SDK

mkdir build
cd build
cmake \
    -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DANDROID_ABI=arm64-v8a \
    -DANDROID_STL=c++_shared \
    -DANDROID_NATIVE_API_LEVEL=29 \
    -DANDROID_SDK=$ANDROID_SDK \
    -DANDROID_NDK=$ANDROID_NDK_HOME \
    -DANDROID_HOME=$ANDROID_SDK \
    -DBUILD_ANDROID_EXAMPLES=OFF \
    -DBUILD_ANDROID_PROJECTS=OFF \
    -DBUILD_FAT_JAVA_LIB=OFF \
    -DBUILD_ITT=OFF \
    -DBUILD_JAVA=OFF \
    -DBUILD_JASPER=OFF \
    -DBUILD_KOTLIN_EXTENSIONS=OFF \
    -DBUILD_OPENEXR=OFF \
    -DBUILD_PACKAGE=OFF \
    -DBUILD_PERF_TESTS=OFF \
    -DBUILD_TBB=OFF \
    -DBUILD_TESTS=OFF \
    -DBUILD_TIFF=OFF \
    -DBUILD_WEBP=OFF \
    -DBUILD_opencv_dnn=OFF \
    -DBUILD_opencv_java=OFF \
    -DBUILD_opencv_java_bindings_gen=OFF \
    -DWITH_ANDROID_MEDIANDK=OFF \
    -DWITH_ANDROID_NATIVE_CAMERA=OFF \
    -DWITH_CAROTENE=OFF \
    -DWITH_CUDNN=OFF \
    -DWITH_IMGCODEC_HDR=OFF \
    -DWITH_IMGCODEC_PFM=OFF \
    -DWITH_IMGCODEC_PXM=OFF \
    -DWITH_ITT=OFF \
    -DWITH_JASPER=OFF \
    -DWITH_OPENEXR=OFF \
    -DWITH_TIFF=OFF \
    -DWITH_WEBP=OFF \
    ..
make -j16
